-- ============================================
-- შეფასებების (reviews) ცხრილი + უფლებები
-- გაუშვი Supabase → SQL Editor-ში ერთხელ
-- უსაფრთხოა — არსებულ მონაცემებს არ შლის
-- ============================================

-- 1) ცხრილი (თუ არ არსებობს)
create table if not exists public.reviews (
  id bigint generated by default as identity primary key,
  master_id bigint,
  rating int,
  rating_timing int,
  rating_quality int,
  rating_price int,
  rating_communication int,
  text text,
  author_name text,
  status text default 'pending',
  created_at timestamptz default now()
);

-- 2) სვეტები (თუ ცხრილი უკვე იყო, მაგრამ სვეტი აკლდა)
alter table public.reviews add column if not exists master_id bigint;
alter table public.reviews add column if not exists rating int;
alter table public.reviews add column if not exists rating_timing int;
alter table public.reviews add column if not exists rating_quality int;
alter table public.reviews add column if not exists rating_price int;
alter table public.reviews add column if not exists rating_communication int;
alter table public.reviews add column if not exists text text;
alter table public.reviews add column if not exists author_name text;
alter table public.reviews add column if not exists status text default 'pending';
alter table public.reviews add column if not exists created_at timestamptz default now();

-- 3) RLS ჩართვა
alter table public.reviews enable row level security;

-- 4) ნებისმიერს შეუძლია შეფასების დატოვება (pending-ში ჩავარდება)
drop policy if exists reviews_anon_insert on public.reviews;
create policy reviews_anon_insert on public.reviews
  for insert to anon, authenticated
  with check ( status = 'pending' );

-- 5) საჯაროდ ჩანს მხოლოდ დამტკიცებული შეფასებები
drop policy if exists reviews_public_read on public.reviews;
create policy reviews_public_read on public.reviews
  for select to anon, authenticated
  using ( status = 'approved' );

-- 6) ადმინს — სრული წვდომა (მოდერაცია: დამტკიცება/წაშლა/ნახვა)
drop policy if exists reviews_admin_all on public.reviews;
create policy reviews_admin_all on public.reviews
  for all to authenticated
  using ( (auth.jwt() ->> 'email') = 'geodigiagro@gmail.com' )
  with check ( (auth.jwt() ->> 'email') = 'geodigiagro@gmail.com' );
